//! Agent-mediated automation client registration and revocation.
//!
//! Implements the spec-required `RegisterClient` and `RevokeClient` RPCs
//! described in `docs/specs/agent.md:86-87`. Both handlers operate on a
//! user-scoped store opened from the request payload, append the
//! corresponding `CLIENT_ADD` / `CLIENT_REVOKE` audit row, and return a
//! metadata-only response. The CLI continues to support a direct write
//! path for offline flows; this surface is the agent-mediated equivalent
//! that thin clients can use without holding the audit key themselves.

use std::path::PathBuf;

use locket_core::ClientId;
use locket_store::{AuditWrite, AutomationClientRecord, Store};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::envelope::{ErrorEnvelope, RequestEnvelope, ResponseEnvelope, SuccessEnvelope};

/// Request payload for `RegisterClient`.
///
/// The agent owns audit-row construction so callers do not need to hold
/// the project audit key. The unlocked project key is consulted via the
/// agent's in-memory unlock cache; missing/expired entries return
/// `UnlockRequired` so callers can prompt for unlock and retry.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RegisterClientRequest {
    /// Project identifier the client is scoped to.
    pub project_id: String,
    /// User-scoped store path, relayed so the agent can append the audit row.
    pub store_path: PathBuf,
    /// Human-readable client name, validated against the same shape the CLI uses.
    pub name: String,
    /// Raw Ed25519 public key (32 bytes).
    pub public_key: [u8; 32],
    /// Storage tag recorded on the metadata row (e.g. `external`, `os-keychain`,
    /// `wrapped-local-file`). The agent itself never persists private key
    /// material — it only records the metadata reference.
    pub storage: String,
    /// Allowed agent actions (`run-policy`, `resolve-reference`,
    /// `scan-known-values`, `redact`).
    pub allowed_actions: Vec<String>,
    /// Allowed command-policy names; wildcard or empty entries are rejected.
    pub allowed_policies: Vec<String>,
    /// Whether the client's private key was generated by Locket itself.
    /// Recorded in the audit metadata only; the agent never holds the key.
    #[serde(default)]
    pub created_by_locket: bool,
}

/// Response for `RegisterClient`.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RegisterClientResponse {
    /// Generated stable identifier for the client.
    pub client_id: String,
    /// Truncated public-key fingerprint recorded on the audit row.
    pub fingerprint: String,
}

/// Request payload for `RevokeClient`.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RevokeClientRequest {
    /// Project the client belongs to.
    pub project_id: String,
    /// User-scoped store path used to look up the row and append audit.
    pub store_path: PathBuf,
    /// Client identifier or project-scoped name.
    pub client: String,
}

/// Response for `RevokeClient`.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RevokeClientResponse {
    /// Resolved client identifier.
    pub client_id: String,
    /// Truncated public-key fingerprint recorded on the audit row.
    pub fingerprint: String,
    /// True when the call transitioned the client from active to revoked.
    /// Already-revoked clients return `false` and the agent skips the audit
    /// row to keep revocation idempotent.
    pub newly_revoked: bool,
    /// Revocation timestamp in nanoseconds since the Unix epoch when newly
    /// revoked, otherwise the previous revocation timestamp.
    pub revoked_at: i64,
}

/// Handler for `RegisterClient`.
#[cfg(unix)]
pub async fn handle_register_client(
    request: &RequestEnvelope,
    state: &crate::server::AgentSocketState,
    now_unix_nanos: i128,
) -> ResponseEnvelope {
    let payload: RegisterClientRequest = match serde_json::from_value(request.payload.clone()) {
        Ok(value) => value,
        Err(_) => return protocol_error(request, "invalid RegisterClient payload"),
    };

    let name = match validate_name(&payload.name) {
        Ok(name) => name,
        Err(message) => return metadata_invalid(request, message),
    };
    let actions = match validate_actions(&payload.allowed_actions) {
        Ok(actions) => actions,
        Err(message) => return metadata_invalid(request, message),
    };
    let policies = match validate_policies(&payload.allowed_policies) {
        Ok(policies) => policies,
        Err(message) => return metadata_invalid(request, message),
    };
    let storage = match validate_storage(&payload.storage) {
        Ok(value) => value,
        Err(message) => return metadata_invalid(request, message),
    };

    let audit_key = match audit_key_for_project(state, &payload.project_id, now_unix_nanos).await {
        Some(key) => key,
        None => return unlock_required(request, "unlock required to register automation client"),
    };

    let mut store = match Store::open(&payload.store_path) {
        Ok(store) => store,
        Err(error) => return corrupt_db(request, format!("failed to open store: {error}")),
    };

    let id = match ClientId::generate() {
        Ok(id) => id,
        Err(error) => return corrupt_db(request, format!("failed to generate client id: {error}")),
    };
    let timestamp = i64::try_from(now_unix_nanos).unwrap_or(i64::MAX);
    let fingerprint = client_public_key_fingerprint(&payload.public_key);
    let record = AutomationClientRecord {
        id: id.as_str().to_owned(),
        project_id: payload.project_id.clone(),
        name: name.to_owned(),
        public_key: payload.public_key.to_vec(),
        fingerprint: fingerprint.clone(),
        storage: storage.to_owned(),
        allowed_actions: actions.clone(),
        allowed_policies: policies.clone(),
        created_at: timestamp,
        last_used_at: None,
        revoked_at: None,
    };
    if let Err(error) = store.insert_automation_client(&record) {
        return corrupt_db(request, format!("failed to insert automation client: {error}"));
    }
    let metadata = json!({
        "schema_version": 1,
        "action": "CLIENT_ADD",
        "status": "SUCCESS",
        "command": "agent client",
        "project_id": payload.project_id,
        "client_id": &record.id,
        "client_name": &record.name,
        "public_key_fingerprint": &fingerprint,
        "storage": &record.storage,
        "allowed_actions": &actions,
        "allowed_policies": &policies,
        "created_by_locket": payload.created_by_locket,
    });
    let audit = AuditWrite {
        project_id: &payload.project_id,
        profile_id: None,
        action: "CLIENT_ADD",
        status: "SUCCESS",
        secret_name: None,
        command: Some("agent client"),
        metadata_json: &metadata,
        timestamp,
    };
    if let Err(error) = store.append_audit(&audit_key, &audit) {
        return corrupt_db(request, format!("failed to append CLIENT_ADD audit row: {error}"));
    }
    success(request, RegisterClientResponse { client_id: record.id, fingerprint })
}

/// Handler for `RevokeClient`.
#[cfg(unix)]
pub async fn handle_revoke_client(
    request: &RequestEnvelope,
    state: &crate::server::AgentSocketState,
    now_unix_nanos: i128,
) -> ResponseEnvelope {
    let payload: RevokeClientRequest = match serde_json::from_value(request.payload.clone()) {
        Ok(value) => value,
        Err(_) => return protocol_error(request, "invalid RevokeClient payload"),
    };

    let audit_key = match audit_key_for_project(state, &payload.project_id, now_unix_nanos).await {
        Some(key) => key,
        None => return unlock_required(request, "unlock required to revoke automation client"),
    };

    let mut store = match Store::open(&payload.store_path) {
        Ok(store) => store,
        Err(error) => return corrupt_db(request, format!("failed to open store: {error}")),
    };

    let client = match store.get_automation_client(&payload.project_id, &payload.client) {
        Ok(Some(client)) => client,
        Ok(None) => {
            return ResponseEnvelope::Error(ErrorEnvelope::new(
                request.id.clone(),
                "PolicyNotFound",
                format!("automation client not found: {}", payload.client),
                false,
            ));
        }
        Err(error) => return corrupt_db(request, format!("failed to look up client: {error}")),
    };

    if let Some(previous) = client.revoked_at {
        return success(
            request,
            RevokeClientResponse {
                client_id: client.id,
                fingerprint: client.fingerprint,
                newly_revoked: false,
                revoked_at: previous,
            },
        );
    }

    let timestamp = i64::try_from(now_unix_nanos).unwrap_or(i64::MAX);
    match store.revoke_automation_client(&payload.project_id, &client.id, timestamp) {
        Ok(true) => {}
        Ok(false) => {
            return ResponseEnvelope::Error(ErrorEnvelope::new(
                request.id.clone(),
                "PolicyNotFound",
                "automation client was revoked concurrently",
                false,
            ));
        }
        Err(error) => return corrupt_db(request, format!("failed to revoke client: {error}")),
    }
    let metadata = json!({
        "schema_version": 1,
        "action": "CLIENT_REVOKE",
        "status": "SUCCESS",
        "command": "agent client",
        "project_id": payload.project_id,
        "client_id": &client.id,
        "client_name": &client.name,
        "public_key_fingerprint": &client.fingerprint,
        "storage": &client.storage,
        "allowed_actions": &client.allowed_actions,
        "allowed_policies": &client.allowed_policies,
        "revoked_at": timestamp,
    });
    let audit = AuditWrite {
        project_id: &payload.project_id,
        profile_id: None,
        action: "CLIENT_REVOKE",
        status: "SUCCESS",
        secret_name: None,
        command: Some("agent client"),
        metadata_json: &metadata,
        timestamp,
    };
    if let Err(error) = store.append_audit(&audit_key, &audit) {
        return corrupt_db(request, format!("failed to append CLIENT_REVOKE audit row: {error}"));
    }
    success(
        request,
        RevokeClientResponse {
            client_id: client.id,
            fingerprint: client.fingerprint,
            newly_revoked: true,
            revoked_at: timestamp,
        },
    )
}

#[cfg(unix)]
async fn audit_key_for_project(
    state: &crate::server::AgentSocketState,
    project_id: &str,
    now_unix_nanos: i128,
) -> Option<Vec<u8>> {
    state
        .unlock_cache
        .lock()
        .await
        .lookup(project_id, now_unix_nanos)
        .map(|entry| entry.key_bytes().to_vec())
}

fn client_public_key_fingerprint(public_key: &[u8; 32]) -> String {
    let digest = Sha256::digest(public_key);
    let mut out = String::with_capacity(32);
    for byte in &digest[..16] {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn validate_name(name: &str) -> Result<&str, &'static str> {
    let name = name.trim();
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err("client name cannot be empty");
    };
    if !first.is_ascii_lowercase()
        || !chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-' || ch == '_')
        || name.len() > 64
    {
        return Err("client name must match ^[a-z][a-z0-9_-]{0,63}$");
    }
    Ok(name)
}

fn validate_actions(actions: &[String]) -> Result<Vec<String>, &'static str> {
    if actions.is_empty() {
        return Err("at least one allowed_action is required");
    }
    let mut normalized = std::collections::BTreeSet::new();
    for action in actions {
        match action.as_str() {
            "run-policy" | "resolve-reference" | "scan-known-values" | "redact" => {
                normalized.insert(action.clone());
            }
            _ => return Err("unsupported automation-client action"),
        }
    }
    Ok(normalized.into_iter().collect())
}

fn validate_policies(policies: &[String]) -> Result<Vec<String>, &'static str> {
    if policies.is_empty() {
        return Err("at least one allowed_policy is required");
    }
    let mut normalized = std::collections::BTreeSet::new();
    for policy in policies {
        if policy == "*" || policy.trim().is_empty() {
            return Err("wildcard or empty client policies are not supported");
        }
        normalized.insert(policy.clone());
    }
    Ok(normalized.into_iter().collect())
}

fn validate_storage(storage: &str) -> Result<&str, &'static str> {
    match storage {
        "external" | "os-keychain" | "wrapped-local-file" => Ok(storage),
        _ => Err("unsupported automation client private-key storage"),
    }
}

fn protocol_error(request: &RequestEnvelope, message: impl Into<String>) -> ResponseEnvelope {
    ResponseEnvelope::Error(ErrorEnvelope::new(request.id.clone(), "ProtocolError", message, false))
}

fn metadata_invalid(request: &RequestEnvelope, message: impl Into<String>) -> ResponseEnvelope {
    ResponseEnvelope::Error(ErrorEnvelope::new(
        request.id.clone(),
        "MetadataInvalid",
        message,
        false,
    ))
}

fn unlock_required(request: &RequestEnvelope, message: impl Into<String>) -> ResponseEnvelope {
    ResponseEnvelope::Error(ErrorEnvelope::new(
        request.id.clone(),
        "UnlockRequired",
        message,
        false,
    ))
}

fn corrupt_db(request: &RequestEnvelope, message: impl Into<String>) -> ResponseEnvelope {
    ResponseEnvelope::Error(ErrorEnvelope::new(request.id.clone(), "CorruptDb", message, false))
}

fn success<T: Serialize>(request: &RequestEnvelope, payload: T) -> ResponseEnvelope {
    let payload = serde_json::to_value(payload).unwrap_or(Value::Null);
    ResponseEnvelope::Success(SuccessEnvelope::new(request.id.clone(), payload))
}
